### ISSUE TITLE
make package null safety

### ISSUE THREAD

**Issue by dhorajiaabhishek** [tomalabaster/flutter_app_lock#16]
Hey @tomalabaster ,
Can you migrate package to null safety.
As I need to migrate my app to null safety

**Comment by tomalabaster** [comment]
Yes! I'm going to write tests now as a 1.5.1 release. Then I'll finish the migration to null-safety as a 2.0.0 release.

**Comment by tomalabaster** [comment]
@dhorajiaabhishek this has been released on pub.dev.
