### ISSUE TITLE
iOS random taps unlock the app

### ISSUE THREAD

**Issue by alexlovar** [tomalabaster/flutter_app_lock#17]
**Describe the bug**
in iOS when the lock screen is showed, if you tap speedily and randomly in the screen without touch the numbers, the look screen closed suddenly and show the active protected screen

**Expected behavior**
screen lock must stay in front unless the correct pin is entered

**Comment by tomalabaster** [comment]
This definitely sounds concerning.

Are you able to provide a minimal repeatable code sample and/or a video please @alexlovar ?

**Comment by alexlovar** [comment]
sorry, is  my fault , something with right swipe on iOS devices.
