### ISSUE TITLE
Localization bugs

### ISSUE THREAD

**Issue by floranguyen0** [tomalabaster/flutter_app_lock#19]
**Describe the bug**

Hi, your plugin is instantiated in the beginning and to pass any initialization of MyApp, you said I need to wrap it in a function but the problem is setLocale is a static function of MyApp. 
An app localized all components except an alertDialog and LockScreen (which is initialized before the localized process).

So, please guide me through how to use your plugin and still be able to localize an entire app, thanks a lot!

**To Reproduce**

Here the codes in main.dart:

`import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_app_lock/flutter_app_lock.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'classes/lockscreen.dart';
import 'database_management/shared_preferences_services.dart';
import 'localization/app_localization.dart';
import 'home.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await sharedPrefs.sharePrefsInit();
  sharedPrefs.setItems(setCategoriesToDefault: false);
  sharedPrefs.getCurrency();
  sharedPrefs.getAllExpenseItemsLists();
  runApp(
      AppLock(
      builder: (args) => MyApp(),
      lockScreen: MainLockScreen(),
      enabled: sharedPrefs.isPasscodeOn ? true : false)
  );
}

class MyApp extends StatefulWidget {
  static void setLocale(BuildContext context, Locale newLocale) {
    _MyAppState state = context.findAncestorStateOfType<_MyAppState>()!;
    state.setLocale(newLocale);
  }

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  late Locale? _locale;
  setLocale(Locale locale) {
    setState(() {
      _locale = locale;
    });
  }

  @override
  void didChangeDependencies() {
    Locale appLocale = sharedPrefs.getLocale();
    setState(() {
      this._locale = appLocale;
    });
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    if (this._locale == null) {
      return Container(
        child: Center(
          child: CircularProgressIndicator(
              valueColor: AlwaysStoppedAnimation<Color>(Colors.blue[800]!)),
        ),
      );
    } else {
      return ScreenUtilInit(
        designSize: Size(428.0, 926.0),
        builder: () => MaterialApp(
          title: 'MMAS',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(primarySwatch: Colors.indigo),
          builder: (context, widget) => MediaQuery(
            data: MediaQuery.of(context).copyWith(textScaleFactor: 1),
            child: widget!,
          ),
          home: Home(),
          locale: _locale,
          localizationsDelegates: [
            AppLocalization.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          localeResolutionCallback: (locale, supportedLocales) {
            for (var supportedLocale in supportedLocales) {
              if (supportedLocale.languageCode == locale!.languageCode &&
                  supportedLocale.countryCode == locale.countryCode) {
                return supportedLocale;
              }
            }
            return supportedLocales.first;
          },
          supportedLocales: [
            Locale("en", "US"),
            Locale("de", "DE"),
            Locale("es", "ES"),
            Locale("fr", "FR"),
            Locale("hi", "IN"),
            Locale("ja", "JP"),
            Locale("ko", "KR"),
            Locale("pt", "PT"),
            Locale("ru", "RU"),
            Locale("tr", "TR"),
            Locale("vi", "VN"),
            Locale("zh", "CN"),
          ],
        ),
      );
    }
  }
}
`

**Comment by tomalabaster** [comment]
Hi! Thanks for raising this. It looks like something like this could be possible using using a solution I proposed [here](https://github.com/tomalabaster/flutter_app_lock/issues/8#issuecomment-807768219).

I'll give it some more work and perhaps ask if you'd be able to trial it out.

**Comment by tomalabaster** [comment]
Hey everyone following this issue! I've just published a pre-release version of AppLock which no longer uses MaterialApp under the hood and changes the implementation to be compatible with your own theming.

If you're able to check it out and it's compatibility with your projects that would be great!: [https://pub.dev/packages/flutter_app_lock/versions/4.0.0-dev.0](https://pub.dev/packages/flutter_app_lock/versions/4.0.0-dev.0)

**Comment by tomalabaster** [comment]
Closing as v4.0.0 resolves this 👍
