### ISSUE TITLE
Please migrate to Flutter 3.0

### ISSUE THREAD

**Issue by rubytech-avsorokin** [tomalabaster/flutter_app_lock#22]
Build has annoying warnings after migration to flutter 3.0

../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_app_lock-2.0.0/lib/src/widgets/app_lock.dart:58:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which
excludes null.

../../../../dev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_app_lock-2.0.0/lib/src/widgets/app_lock.dart:88:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which
excludes null.

Could You release version for 3.0?

**Comment by tomalabaster** [comment]
Sure thing! Doing that this evening.

**Comment by tomalabaster** [comment]
Done! It's now available on pub.dev
