### ISSUE TITLE
Lock function, as an alternative to lock screen.

### ISSUE THREAD

**Issue by tobiasht** [tomalabaster/flutter_app_lock#23]
**Is your feature request related to a problem? Please describe.**
In many apps you want to sign the user out of the app completely, not just show a screen overlay. This is especially important when handling sensitive information. My suggestion is to have an optional **lock function** which is triggered when the app is locked. This would also make it easy to integrate this package with existing applications which already have a sign in/pin code functionality. And would go great with feature request #10. 

Both lockScreen and lockFunction should be be optional, but minimum one should be defined. 

**Describe the solution you'd like**
Have a lock function, which is triggered when the app is locked. Either instead of the lock screen overlay or as an addition.

**Describe alternatives you've considered**
This could be it own package, but i think the similarities between the functionalities are too similar to split up since they are both triggered on the same trigger.

**Comment by tomalabaster** [comment]
Hi!

I'm sorry, I don't quite follow what the expected behaviour is here?

**Comment by tobiasht** [comment]
Feature request #10 Lock after inactivity, relates to locking the user out of the app after a set amount of time. In many cases there would be beneficial to run a _function_ when this timer ends, not just showing a lock screen. Then it would be up to the user, if they wanted to run a sign out function in addition (or instead ) of showing the lock screen.

My request would look something like this. 
```dart
void main() {
  runApp(AppLock(
    builder: (arg) => MyApp(data: arg),
    lockScreen: LockScreen(),            // Optional (but at least one of the two)
    lockFunction:  () => LockFunction(), // Optional
  ));
}
```

**Comment by tomalabaster** [comment]
That has been added to version 4.1.0! https://pub.dev/packages/flutter_app_lock/versions/4.1.0
