### ISSUE TITLE
AppLock for FlutterFlow

### ISSUE THREAD

**Issue by baptiste-veyrard** [tomalabaster/flutter_app_lock#29]
Hello,

More and more people are using low-code tools like FlutterFlow to create apps, it is my case.

I am building an application where the security is key.
In order to add a local security layer on my app, I would like to add the biometric authentication when the app starts and when the app is resumed (after being in the background).

Currently, I am doing this in the following way:
- I added a custom action in my main.dart file, which add a lifecycle observer
- When the app start, I trigger the biometric authentication and I set the lifecycle observer
- When the app is "resumed" in the lifecycle, I trigger the biometric authentication

I am not sure about the security of this flow.

I found your flutter pub and It seems to be more secure about the app start given the whole app seems to be wrapped in an AppLock widget, so it conditionally loads the rest of the app according to the auth result (if I am not wrong).
About the app resume, it seems to do the same thing I have done.

**According to you, the pub is more robust than my current flow?**

**Do you know if there is a way to use this pub in FlutterFlow?**

According to the doc, the BuildContext seems to be required to override the native behavior.
Unless I am wrong, we cannot use the BuildContext in a FlutterFlow custom action that we would add to the main.dart file via FlutterFlow.

In a custom action, I do not know how to override the class MyApp.

Let me know if this is not the proper place for this kind of question.
Thanks

**Comment by tomalabaster** [comment]
Hi! I'm not best placed to say whether this package is more secure/robust than your logic - only you can make that assessment.

As to making this available in FlutterFlow, if you can provide some documentation about how 3rd party packages are able to be used in FlutterFlow than it's something I can look into.

**Comment by baptiste-veyrard** [comment]
Hi, thanks for your answer.

With FlutterFlow, we can add custom code, either within FlutterFlow itself (via [Custom Action](https://docs.flutterflow.io/customizing-your-app/custom-functions/custom-actions) or [Custom Widget](https://docs.flutterflow.io/customizing-your-app/custom-functions/custom-widgets)), or modifying the Dart code locally (after downloading the code or a push to github).

Initially, I would have preferred to do it into FlutterFlow to avoid conflict when I merge my FlutterFlow code and my custom code locally, given main.dart is quite sensitive and that any change on FlutterFlow could cause conflicts when merging with my custom code.

Within the FlutterFlow UI, e can [modify the main.dart](https://docs.flutterflow.io/customizing-your-app/custom-functions/custom-files#edit-main.dart) code but with many limitation. It is only possible to add Custom Action that has no BuildContext as parameter (Photo attached). 

But given the runApp will always be the last action performed, I do not think it is possible to override it before it is called.
So maybe I can do it out of FlutterFlow directly within the main.dart file. 
Find below what looks the code of the main.dart file generated by FlutterFlow.

Do you think is it possible to integrate app_lock ?

'''
import '/custom_code/actions/index.dart' as actions;
import 'package:provider/provider.dart';
import 'package:flutter/material.dart';

import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_web_plugins/url_strategy.dart';
import 'auth/firebase_auth/firebase_user_provider.dart';
import 'auth/firebase_auth/auth_util.dart';

import 'backend/firebase/firebase_config.dart';
import 'flutter_flow/flutter_flow_theme.dart';
import 'flutter_flow/flutter_flow_util.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  usePathUrlStrategy();
  await initFirebase();

  await FlutterFlowTheme.initialize();

  final appState = FFAppState(); // Initialize FFAppState
  await appState.initializePersistedState();

  // Start final custom actions code
  await actions.appLifecycle();
  // End final custom actions code

  runApp(ChangeNotifierProvider(
    create: (context) => appState,
    child: const MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  State<MyApp> createState() => _MyAppState();

  static _MyAppState of(BuildContext context) =>
      context.findAncestorStateOfType<_MyAppState>()!;
}

class _MyAppState extends State<MyApp> {
  ThemeMode _themeMode = FlutterFlowTheme.themeMode;

  late Stream<BaseAuthUser> userStream;

  late AppStateNotifier _appStateNotifier;
  late GoRouter _router;

  final authUserSub = authenticatedUserStream.listen((_) {});

  @override
  void initState() {
    super.initState();

    _appStateNotifier = AppStateNotifier.instance;
    _router = createRouter(_appStateNotifier);
    userStream = simpliPassMobileFirebaseUserStream()
      ..listen((user) => _appStateNotifier.update(user));
    jwtTokenStream.listen((_) {});
    Future.delayed(
      const Duration(milliseconds: 1000),
      () => _appStateNotifier.stopShowingSplashImage(),
    );
  }

  @override
  void dispose() {
    authUserSub.cancel();

    super.dispose();
  }

  void setThemeMode(ThemeMode mode) => setState(() {
        _themeMode = mode;
        FlutterFlowTheme.saveThemeMode(mode);
      });

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'SimpliPass Mobile',
      localizationsDelegates: const [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [Locale('en', '')],
      theme: ThemeData(
        brightness: Brightness.light,
        useMaterial3: false,
      ),
      darkTheme: ThemeData(
        brightness: Brightness.dark,
        useMaterial3: false,
      ),
      themeMode: _themeMode,
      routerConfig: _router,
    );
  }
}
'''
<img width="1173" alt="Photo 1" src="https://github.com/tomalabaster/flutter_app_lock/assets/48984863/48e346bb-d089-4795-8348-66a6a7816d20">

**Comment by tomalabaster** [comment]
Hello! Thanks for providing me with the documentation and examples.

Unfortunately I can't see how the code around the `MaterialApp.router` can be customised using Flutter Flow which is where the code for flutter_app_lock would need to go.

I'm going to close this issue, it may be worth looking at a forum or community specific to Flutter Flow for this.

All the best!

**Comment by jasjastone** [comment]
Hello Mate,
I have use AppLock with the MaterialApp.router this way

```dart
Widget build(BuildContext context) {
    return MaterialApp.router(
      title: AppConfig.appName,
      debugShowCheckedModeBanner: AppConfig.appDebug,
      //... other params
      builder: (context, child) => AppLock(
        builder: (context, arg) => child!,
        lockScreenBuilder: (context) => const PasswordScreen(),//this is the screen with password or bio metric authentication logic
        initiallyEnabled: true,//put it to false if you want to enable it after login like i did but from your description leave this as it
        initialBackgroundLockLatency: Duration.zero,//locks as soon as the user minimizes the app
      ),
      routeInformationProvider: ROUTER.routeInformationProvider,
      routeInformationParser: ROUTER.routeInformationParser,
      routerDelegate: ROUTER.routerDelegate,
    );
  }
```
